name = "national-outage-street-manager"
main = "src/index.ts"
compatibility_date = "2026-09-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "national-outage-street-manager"
database_id = "fbba3cee-e93a-44a0-923c-815bb5884bc0"
migrations_dir = "migrations"
